docs(nx): update workspace/init with pipeline changes
amido/amido.github.io pull request #293
Opened 2023-02-09 15:25 UTC by CerdenAmido

#### 📲 What

A description of the change.

#### 🤔 Why
		
Why it's needed, background context.
		
#### 🛠 How
		
More in-depth discussion of the change or implementation.

#### 👀 Evidence
		
Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR.
		 
#### 🕵️ How to test

Notes on how a reviewer can test the changes, e.g. how to run the tests.

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

2023-02-09 16:16 UTC, Danphillipz requested changes
1. Prerequisites: The infra requires various values to be set via the stacks CLI or the create-workspace script. 
2. May need a discussion to decide on where we document the values which drive infra related files (point 1 should link to this)

2023-02-09 16:20 UTC, CerdenAmido commented on docs/nx/workspace/init.md
> +If `--pipelineRunner=true` is passed, the generator will also create a `build` directory:
Whoops, thank you

2023-02-09 16:26 UTC, CerdenAmido commented
> 1. Prerequisites: The infra requires various values to be set via the stacks CLI or the create-workspace script.

To clarify my understanding on this - normally we run this generator under the hood as part of `create-stacks-workspace`. At this point, we check if `stacks.json` has certain fields, which it always should at this point, and if it doesn't we pass `--pipelineRunner=none`. We *don't* want to document this here because it's not really a prerequisite of the generator as such. The generator itself checks whether the stacks config has a `pipeline` field, or whether the `build` folder already exists, and doesn't create the pipeline folder in either case. We *do* want to document this here as it's the generator doing the work.

Is that assessment correct?

2023-02-09 16:58 UTC, Danphillipz commented
> 

Yes this is normally ran under the hood, but can also be ran independently to 'stackify' an existing nx workspace. 

You're correct, I don't think we do want to document all of the values which this generator requires as a prereq for infra as it's common across this and the next:infrastructure generator. However I think we should at least say, in order to generate infrastructure for your application the following dependendecies must be in place (with a link to where this is documented)

2023-02-10 14:21 UTC, Danphillipz approved these changes

2023-02-10 14:22 UTC, merged