Update next-auth with redis info
amido/amido.github.io pull request #302
Opened 2023-03-01 15:24 UTC by Danphillipz

#### 📲 What

A description of the change.

#### 🤔 Why
		
Why it's needed, background context.
		
#### 🛠 How
		
More in-depth discussion of the change or implementation.

#### 👀 Evidence
		
Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR.
		 
#### 🕵️ How to test

Notes on how a reviewer can test the changes, e.g. how to run the tests.

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

2023-03-01 17:04 UTC, Danphillipz commented on docs/nx/create-stacks-workspace/plugin-information.md
> +| --cloudplatform | Name of the cloud provider  | string    | azure                  | azure     |
```suggestion
| --cloud.platform | Name of the cloud provider  | string    | azure                  | azure     |
```

2023-03-02 10:24 UTC, johnmckenna requested changes

2023-03-02 10:24 UTC, johnmckenna commented on docs/nx/next/next-auth-redis.md
> +```typescript title="<app-name>/project.json will have the helm-upgrade commands updated to use the NEXTAUTH_SECRET"
"for Azure DevOps this needs added to the \<company>-\<component>-\<domain>-nonprod and \<company>-\<component>-\<domain>-prod' variable groups"

2023-03-02 10:56 UTC, johnmckenna approved these changes

2023-03-02 10:59 UTC, merged